### ISSUE TITLE
Kubernetes environmental bindings support

### ISSUE THREAD

**Issue by jcantosz** [germanattanasio/vcap-services#14]
If `VCAP_SERVICES` is not available, I would like to fall back to an environment variable named with the service instance name.

Use Case: I would like to use this module inside the Kubernetes. When binding a service to a pod, `VCAP_SERVICES` is not set. When the service is bound, a secret with the credentials JSON as a string is created. This credentials JSON is of the same as the output of this module when `VCAP_SERVICES` is present. If this secret is bound to an environmental variable of that begins with the service name, and this change is implemented, returning the JSON would for this scenario would make cf to k8s conversion simple

**Comment by germanattanasio** [comment]
Hei @jcantosz  Can you help with a PR?

**Comment by germanattanasio** [comment]
fixed in #15
