### ISSUE TITLE
Module errors when environment variables defined that match service name

### ISSUE THREAD

**Issue by wallali** [germanattanasio/vcap-services#17]
This module is no longer what it says on the tin. If VCAP_SERVICES is not defined it is now trying to parse the process.env and read variables in the environment that have a name that matches the service.

https://github.com/germanattanasio/vcap-services/blob/master/index.js#L47

So I have a environment variable CONVERSATION_WORKSPACE_ID which now causes an issue:

```
Error parsing JSON from process.env.CONVERSATION_WORKSPACE_ID
SyntaxError: Unexpected token f in JSON at position 1
```
Why is this module trying to read my CONVERSATION_WORKSPACE_ID as a json. I never asked it to. VCAP_SERVICES is not defined in my environment so it should leave my environment alone.

Note: I don't even use this module. I land up here because of https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/base_service.js#L69

**Comment by germanattanasio** [comment]
Hi @wallali, we added this feature in #14.
I think you are right we should not use [`.startWith()`](https://github.com/germanattanasio/vcap-services/blob/master/index.js#L47)
@jcantosz I think I'm we need to change the code you added. Right the module is doing more than reading the `VCAP_SERVICES`. We need to find a solution to run this module in kubernetes without affecting other users.

**Comment by germanattanasio** [comment]
@wallali I've removed the fuzzy match. Sorry for the troubles.

**Comment by jcantosz** [comment]
@germanattanasio I was initially doing the fuzzy match to automatically support the Watson node SDK (https://github.com/watson-developer-cloud/node-sdk) as it does not appear that an instance can be specified. I know that that support is outside the scope of this library. 

We can suppress the warning, but as before there may be unintended consequences for users that have similarly name ENV variables. Is there a good way we can solve both cases?
