### ISSUE TITLE
Should try to read from local credential file

### ISSUE THREAD

**Issue by jsstylos** [germanattanasio/vcap-services#5]
Having users copy and paste username and passwords into particular variables is error prone. It would be better to have users copy and paste their entire environment into a JSON file. To support this, the vcap_services module should check for the existence a file in the root directory with a certain name and load it in.

**Comment by wallali** [comment]
Try using https://www.npmjs.com/package/dotenv

**Comment by germanattanasio** [comment]
I agree with @wallali. I like the idea of loading credentials from a file but not something this module should support
